# Generated by Django 3.2.5 on 2021-07-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='onwer',
            new_name='owner',
        ),
    ]
